# Generated by Django 2.0.1 on 2018-01-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=100, verbose_name='演员')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20, verbose_name='国家名')),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='static/images', verbose_name='封面')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('date', models.DateField(verbose_name='上映时间')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('country', models.ManyToManyField(related_name='movieconutry', to='movie.country')),
                ('m_actors', models.ManyToManyField(related_name='actorname', to='movie.actors')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='电影类型')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.ManyToManyField(related_name='movietype', to='movie.type'),
        ),
        migrations.AddField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviecomments', to='movie.movies'),
        ),
    ]
